version: '3'

env:
  COMPOSE_PROJECT_NAME: mage_bus
  UID:
    sh: 'if [ `echo $(id -u) -lt 1000` ]; then echo 1000; else echo $(id -u); fi'
  GID:
    sh: 'if [ `echo $(id -g) -lt 1000` ]; then echo 1000; else echo $(id -g); fi'

tasks:
  build:
    cmds:
    - UID=$UID GID=$GID docker-compose -f .docker/docker-compose.yml -p $COMPOSE_PROJECT_NAME build --compress --pull --no-cache --force-rm
  down:
    cmds:
    - UID=$UID GID=$GID docker-compose -f .docker/docker-compose.yml -p $COMPOSE_PROJECT_NAME down
  clear:
    cmds:
    - UID=$UID GID=$GID docker-compose -f .docker/docker-compose.yml -p $COMPOSE_PROJECT_NAME down --rmi all
  php:
    cmds:
    - UID=$UID GID=$GID docker-compose -f .docker/docker-compose.yml -p $COMPOSE_PROJECT_NAME run --rm --service-ports php {{.CLI_ARGS}}
  composer:
    cmds:
    - task: php
      vars: {CLI_ARGS: 'composer {{.CLI_ARGS}}'}
